<!-- Js Plugins -->
<script src="<?= CLIENT_ASSET ?>js/jquery-3.3.1.min.js"></script>
<script src="<?= CLIENT_ASSET ?>js/bootstrap.min.js"></script>
<script src="<?= CLIENT_ASSET ?>js/jquery.nice-select.min.js"></script>
<script src="<?= CLIENT_ASSET ?>js/jquery-ui.min.js"></script>
<script src="<?= CLIENT_ASSET ?>js/jquery.slicknav.js"></script>
<script src="<?= CLIENT_ASSET ?>js/mixitup.min.js"></script>
<script src="<?= CLIENT_ASSET ?>js/owl.carousel.min.js"></script>
<script src="<?= CLIENT_ASSET ?>js/main.js"></script>